language: java
jdk: oraclejdk8

jobs:
  include:
    # Stage Test - Job 1-3:  Builds against all Jdks.
      script: mvn -q install
    - jdk: oraclejdk8
      script: mvn -q install
    # Stage Test - Job 4: Build Android Examples.
    - jdk: oraclejdk8
      env: ANDROID_EXAMPLES=true
      language: android
      android:
        components:
          - tools
          - platform-tools
          - tools # Note that the tools section appears twice on purpose as it’s required to get the newest Android SDK tools.
          - build-tools-26.0.0
          - android-21
          - sys-img-armeabi-v7a-android-21

